#!/usr/bin/env bash
clear

# Set up the shell variables for colors
# http://stackoverflow.com/questions/5947742/how-to-change-the-output-color-of-echo-in-linux
yellow='\033[1;33m'
green='\033[0;32m'     
red='\033[0;31m'     
clear='\033[0m';

echo -e  "${green}"
echo "============================================"
echo ""
echo "Installing Dotfiiles"
echo ""
echo "============================================"
echo -e  "${clear}"

if [ -z "$HOME" ]; then echo "Seems you're \$HOMEless :("; exit 1; fi

DOTFILES=$HOME/.dotfiles
DOTFILESOLD=$HOME/.dotfiles.old
DOTLOCAL=$HOME/.local/share/dotfiles
GITCLONE="git clone --depth=1 --quiet"


echo -n "Backup into '$DOTFILESOLD'... "
mv \
    "$HOME/.zshrc" \
    "$HOME/.vimrc" \
    $DOTFILESOLD
echo -e ${green}done${clear}


echo -e "Removing\n $DOTFILES\n $DOTLOCAL"
read -p "Are you sure? [Y/n] " -n 1 -r

if [[ $REPLY =~ ^[Nn]$ ]]; then 
    exit
fi

echo -n "Removing current dotfiles... "
rm -rf \
    $DOTFILES \
    $DOTLOCAL
echo -e ${green}done${clear}


echo "Making directories... "
mkdir -pv "$DOTFILES" "$DOTFILESOLD" "$DOTLOCAL"
echo -e ${green}done${clear}


echo -n "Cloning dotfiles from github... "
$GITCLONE https://github.com/gilherr/dotfiles.git $DOTFILES
echo -e ${green}done${clear}


echo -n "Soft linking all dotfiles... "
ln -s "$DOTFILES/vimrc" "$HOME/.vimrc"
ln -s "$DOTFILES/zshrc" "$HOME/.zshrc"
ln -s "$DOTFILES/tmux.conf" "$HOME/.tmux.conf"
echo -e ${green}done${clear}


echo -n "Cloning fzf... "
if [ ! -f ~/.fzf.zsh ]
then 
    $GITCLONE https://github.com/junegunn/fzf.git "$DOTLOCAL/fzf"
    "$DOTLOCAL/fzf/install" --key-bindings --completion --no-update-rc
fi
echo -e ${green}done${clear}


echo -n "Cloning zsh plugins... "
ZSHPLUGS=(
  "zsh-syntax-highlighting"
  "zsh-autosuggestions"
)
for INDEX in ${!ZSHPLUGS[*]}; do
  ZSHPLUG="${ZSHPLUGS[$INDEX]}"
  $GITCLONE "https://github.com/zsh-users/$ZSHPLUG.git" "$DOTLOCAL/zsh/$ZSHPLUG" >/dev/null
done
echo -e ${green}done${clear}

echo -n "Cloning tmux plugins... "
$GITCLONE "https://github.com/jimeh/tmux-themepack.git" "$DOTLOCAL/tmux-themepack"
echo -e ${green}done${clear}

# # TODO auto install Silver Searcher to find in all files on vim
# # ubuntu: apt-get install silversearcher-ag
# # arch:  pacman -S the_silver_searcher
