#!/usr/bin/env bash

if [ -z "$HOME" ]; then echo "Seems you're \$HOMEless :("; exit 1; fi

DOTFILES=$HOME/.dotfiles
DOTFILESOLD=$HOME/.dotfiles.old
DOTLOCAL=$HOME/.local/share/dotfiles

GITCLONE="git clone --depth=1"

mkdir -p "$DOTFILES" "$DOTFILESOLD" "$DOTLOCAL/zsh"

mv \
    "$HOME/.zshrc" \
    "$HOME/.vimrc" \
    $DOTFILESOLD

rm -rf \
    $DOTFILES \
    $DOTLOCAL

$GITCLONE https://github.com/gilherr/dotfiles.git $DOTFILES

ln -s "$DOTFILES/vimrc" "$HOME/.vimrc"
ln -s "$DOTFILES/zshrc" "$HOME/.zshrc"

if [ ! -f ~/.fzf.zsh ]
then 
    $GITCLONE https://github.com/junegunn/fzf.git "$DOTLOCAL/fzf"
    "$DOTLOCAL/fzf/install" --key-bindings --completion --no-update-rc
fi


ZSHPLUGS=(
  "zsh-syntax-highlighting"
  "zsh-autosuggestions"
)


for INDEX in ${!ZSHPLUGS[*]}; do
  ZSHPLUG="${ZSHPLUGS[$INDEX]}"
  echo "----- $ZSHPLUG -----"
  $GITCLONE "https://github.com/zsh-users/$ZSHPLUG.git" "$DOTLOCAL/zsh/$ZSHPLUG"
done

# TODO auto install Silver Searcher to find in all files on vim
# ubuntu: apt-get install silversearcher-ag
# arch:  pacman -S the_silver_searcher

# VIMPLUGS=(
#     "scrooloose/nerdtree"
#     "vim-airline/vim-airline"
#     "sickill/vim-monokai"
# )

# for INDEX in ${!VIMPLUGS[*]}; do
#   VIMPLUG="${VIMPLUGS[$INDEX]}"
#   PLUGDIR=$(echo "$VIMPLUG" | cut -d '/' -f2)

#   $GITCLONE "https://github.com/$VIMPLUG.git" "$HOME/.vim/pack/plugins/start/$PLUGDIR"
# done
#!/bin/bash
# .make.sh
# This script creates symlinks from ~/ to dotfiles dir




# ------------------------ from set-dots.sh ----------------------- #

# dir=~/dotfiles
# olddir=~/dotfiles_old
# files=".vimrc .zshrc"

# echo "Creating $olddir for backup of any existing dotfiles in ~"
# mkdir -p $olddir
# echo "...complete."

# echo "Changing to the $dir directory"
# cd $dir
# echo "...complete."

# for file in $files; do
#     echo "Moving existing dotfiles from ~ to $olddir"
#     mv ~/$file $olddir/
#     echo "Creating symlink to $file in home directory."
#     ln -s $dir/$file ~/$file
# done
