#!/usr/bin/env bash

if [ -z "$HOME" ]; then echo "Seems you're \$HOMEless :("; exit 1; fi

DOTFILES=$HOME/.dotfiles
DOTFILESOLD=$HOME/.dotfiles.old
DOTFZF=$HOME/.fzf

GITCLONE="git clone --depth=1"

mkdir -p "$DOTFILES" "$DOTFILESOLD" "$HOME/.zsh"

$GITCLONE https://github.com/gilherr/dotfiles.git $DOTFILES

mv \
    "$HOME/.zshrc" \
    "$HOME/.vimrc" \
    $DOTFILESOLD/

ln -s "$DOTFILES/vimrc" "$HOME/.vimrc"
ln -s "$DOTFILES/zshrc" "$HOME/.zshrc"

$GITCLONE https://github.com/junegunn/fzf.git "$DOTFZF"
"$DOTFZF/install" --key-bindings --completion --no-update-rc


ZSHPLUGS=(
  "zsh-syntax-highlighting"
)


for INDEX in ${!ZSHPLUGS[*]}; do
  ZSHPLUG="${ZSHPLUGS[$INDEX]}"
  $GITCLONE "https://github.com/zsh-users/$ZSHPLUG.git" "$HOME/.zsh/$ZSHPLUG"
done

VIMPLUGS=(
    "scrooloose/nerdtree"
    "vim-airline/vim-airline"
    "sickill/vim-monokai"
)

for INDEX in ${!VIMPLUGS[*]}; do
  VIMPLUG="${VIMPLUGS[$INDEX]}"
  PLUGDIR=$(echo "$VIMPLUG" | cut -d '/' -f2)

  $GITCLONE "https://github.com/$VIMPLUG.git" "$HOME/.vim/pack/plugins/start/$PLUGDIR"
done
